language: python

services:
  - postgresql

before_script:
- psql -c 'create database vbp;' -U postgres
- pip install -r requirements.txt
- python manage.py makemigrations
- python manage.py migrate

script:
  - tox

after_success:
- coveralls
